### PR TITLE
Update Hugo Jourdan Script + Adding new Plugins

### PR DESCRIPTION
**Pull request by HugoJourdan**
Update Hugo Jourdan Script and adding new 3 plugins:
Font Dashboard
Show Master Dashboard
Color Flow

### CODE REVIEW

**Comment by florianpircher** [comment]
I am getting some `'NoneType' object is not iterable` console messages from the Color Flow plugin. Generally, it’s better for a plugin to crash than to catch exceptions and fail silently.

**Comment by HugoJourdan** [comment]
I forgot to push release commit, it's fixed.

**Comment by florianpircher** [comment]
There appears to be an issue when opening multiple documents. I first opened a font with 4069 glyphs and then a new empty file with 66 glyphs, but Color Flow still shows the glyph count and checked checkboxes of the other window even though I did not click any checkbox in the new font:

**Comment by HugoJourdan** [comment]
I know this issue, but I don't know how to fix it for the moment.
For now Color Flow panel show only data to the first opened file.

**Comment by florianpircher** [comment]
The Info directory is used by Glyphs already for some other purposes, so to avoid file name conflicts consider using a less generic name for the `color.txt` file, for example, `Color Names.txt` or `com.hugojourdan.ColorNames.txt`.

Otherwise, the Font Dashboard and Show Master Dashboard plugins look good to me.

**Comment by HugoJourdan** [comment]
Ok, I changed it to `ColorNames.txt`.
Thanks Florian

**Comment by HugoJourdan** [comment]
> There appears to be an issue when opening multiple documents. I first opened a font with 4069 glyphs and then a new empty file with 66 glyphs, but Color Flow still shows the glyph count and checked checkboxes of the other window even though I did not click any checkbox in the new font:
> 
> 

I fixed it

**Pull request merged**
