### PR TITLE
adding a Anchor Arranger plugin

### PR DESCRIPTION
**Pull request by wsimm**
Note: Please add new plugins and scripts to the end of the `plugins = ( ... )` or `scripts = ( ... )` list.

### CODE REVIEW

**Comment by schriftgestalt** [comment]
Next time, please make sure to use tabs for indentation.

**Comment by schriftgestalt** [comment]
And you put it into the scripts group, not into the plugins.

**Comment by schriftgestalt** [comment]
And use the right plugin reference

**Comment by wsimm** [comment]
next time I will make sure to follow these notes carefully, for this time will i have to do these steps or it's going to be done by your side?

Thank You

**Comment by schriftgestalt** [comment]
I fixed it.

**Comment by wsimm** [comment]
Thank you Again

**Comment by florianpircher** [comment]
There were two more issues: The repository does not have a `Glyphs3` branch and the `maxVersion` attribute prevented installing this plugin in the latest version of Glyphs. I removed both of those lines to fix that: https://github.com/schriftgestalt/glyphs-packages/commit/67fc8dd45a3d205f886216b2567df02774457011

**Pull request merged**
