### PR TITLE
add new plugin : Gradient Hatch

### PR DESCRIPTION
**Pull request by tcarisland**
add new plugin = Gradient Hatch

### CODE REVIEW

**Comment by florianpircher** [comment]
Hi, thank you for adding this plugin. I cannot get the gradient to work, all lines have the same distance:

Bildschirmfoto 2024-02-14 um 17 07 47

Am I doing something wrong?

**Comment by tcarisland** [comment]
This seems correct, which version of Glyphs are you using?

**Comment by tcarisland** [comment]
Can you see any error messages in the Macro Panel?

**Comment by tcarisland** [comment]
Skjermbilde 2024-02-14 kl  17 11 13

This is the output I get when I try the same values.

**Comment by florianpircher** [comment]
I will move this discussion to the issues on your repo:

https://github.com/tcarisland/GradientHatch/issues/39

**Comment by tcarisland** [comment]
1. Initial bug was caused by locale-specific code, fixed by using layer.ascender and layer.descender in https://github.com/tcarisland/GradientHatch/issues/39
2. The locale issues were fixed by removing automatically translated locale strings, might ask around in the forum for better translations. Created separate issue for layout challenges. https://github.com/tcarisland/GradientHatch/issues/41
3. A bug was discovered that allowed for negative numbers in the stepWidth. Failsafes and constraints added in https://github.com/tcarisland/GradientHatch/issues/40

**Comment by tcarisland** [comment]
Ready for merge unless something else blocks

**Comment by florianpircher** [comment]
Works well, thank you!

**Pull request merged**
