### PR TITLE
Show Coordinates Distance Angle plugin added

### PR DESCRIPTION
**Pull request by michaelrafailyk**
> **Note**: Please add new plugins and scripts at the end of the `plugins = ( ... )` or `scripts = ( ... )` lists.

### CODE REVIEW

**Comment by schriftgestalt** [comment]
It might be nice to add an screenshot?

**Comment by michaelrafailyk** [comment]
Sure, just a moment..

**Comment by michaelrafailyk** [comment]
Just added a screenshot

**Comment by florianpircher** [comment]
The screenshot needs to point to the image file directly, for example:

```
https://raw.githubusercontent.com/michaelrafailyk/ShowCoordinatesDistanceAngle/main/ShowCoordinatesDistanceAngle.png
```

**Comment by florianpircher** [comment]
Ha, perfect, you already fixed it! :)

**Comment by michaelrafailyk** [comment]
Yes I also just realized it. Updated.

**Comment by florianpircher** [comment]
The plugin works for me, thank you!

**Comment by michaelrafailyk** [comment]
Cool! )

**Comment by michaelrafailyk** [comment]
I'm sorry, can I ask – how to delete the branch from my repositories? Or should I keep this branch for a some reason?

**Comment by michaelrafailyk** [comment]
I mean to delete the fork from my repositories

**Comment by florianpircher** [comment]
Your branch (and fork) is only needed for the pull request. You can delete it now.

**Comment by michaelrafailyk** [comment]
I understood, thank you for explaining!

**Pull request merged**
