### PR TITLE
Update packages.plist

### PR DESCRIPTION
**Pull request by wsimm**
True Glyph plugin added from 
https://github.com/wsimm/True-Glyph

> **Note**: Please add new plugins and scripts at the end of the `plugins = ( ... )` or `scripts = ( ... )` lists.

### CODE REVIEW

**Comment by florianpircher** [comment]
Hi, thank you for submitting your plugin! Looks great!

I tried the plugin with this Edit View setup:



Here is what the export dialog looks like for me:



And this is the resulting PDF:



The glyphs appear in the reverse direction and are partially out of frame.

After the export, a new empty tab is opened in my Glyphs window and the tool of the previous tab (in the example above, the tab with the word “Tangente“) switched to the Pen tool.

Your readme states that the plugin is licensed under the MIT License, but the license file is the GPL 3.0.

***

If you have any questions about the Glyphs API or how to approach the issues above, feel free to ask! However, expect replies to be delayed until after Easter (1st of April).

**Comment by wsimm** [comment]
Sorry for the delay; I didn't notice your feedback.

The glyphs appear in reverse direction and are partially out of frame.
- I solved this issue by adjusting the type direction based on preview direction.
After exporting, a new empty tab opens in my Glyphs window, and the tool...
- The way of exporting any look, especially similar to a glyph look, has combined all typed glyphs into one single glyph. It creates a new glyph called "exportedPreviewPleaseDeleteit" , and after that, it deletes the glyph, but the tab remains open; yet I couldn't find a way to close it.

- The license changed to the MIT License.
Please let me know if there's anything that needs to be fixed; I will be glad to work on it.
Thank you

**Comment by wsimm** [comment]
@florianpircher  any update?

**Comment by florianpircher** [comment]
Sorry for not getting back yet, I will have more time later today.

**Comment by florianpircher** [comment]
I just tested it and it works! There are still some layout issues with the text sometimes shifting out on the right edge, but that might just be my problem for setting the scale incorrectly.

For closing tabs, have a look here:

https://forum.glyphsapp.com/t/how-to-close-all-tabs-via-script/4039

**Pull request merged**
