### PR TITLE
Add Rainbow FontView Plugin

### PR DESCRIPTION
**Pull request by HugoJourdan**

### CODE REVIEW

**Comment by florianpircher** [comment]
The plugin crashes if there is no colorNames.txt file.

Bildschirm­foto 2023-02-17 um 14 06 08

Consider using a default value if there is no file or create the file when it does not yet exist.

**Comment by HugoJourdan** [comment]
I fixed it but forgot to push the commit.
Now it's fixed.

**Comment by florianpircher** [comment]
Hm, I still get a crash on first run:

Bildschirm­foto 2023-02-21 um 00 35 22

**Comment by HugoJourdan** [comment]
I fixed another issues about emoji in .txt file.
I tried to run it without any other plugin and without /info folder and it work.

**Comment by florianpircher** [comment]
The plugin is reading from a path that expects your user name:

```python
with open("/Users/hugojourdan/Library/Application Support/Glyphs 3/info/colorNames.txt", 'w', encoding='utf8') as f:
```

Bildschirm­foto 2023-02-21 um 13 47 09

**Comment by HugoJourdan** [comment]
I forgot this one.
Fixed.

**Comment by florianpircher** [comment]
Here, you check whether the string of the path is not None, but the string always exists. You need to check whether a file at that path exists instead:

```python
if not f"{GSGlyphsInfo.applicationSupportPath()}/info":
	os.makedirs(f"{GSGlyphsInfo.applicationSupportPath()}/info")
```

Bildschirm­foto 2023-02-21 um 14 09 55

And I believe that using the key file next to a Glyphs file does not work as `keyFile` is always overwritten before being returned.

**Comment by schriftgestalt** [comment]
It might be better to move this discussion into the rainbow repo.

**Comment by HugoJourdan** [comment]
```python
if not f"{GSGlyphsInfo.applicationSupportPath()}/info":
	os.makedirs(f"{GSGlyphsInfo.applicationSupportPath()}/info")
```
applicationSupportPath alway exist, but not "info" folder, that's what I'm checking here.

> And I believe that using the key file next to a Glyphs file does not work as keyFile is always overwritten before being returned.

You are right, I fixed it.

**Comment by HugoJourdan** [comment]
I think the plugin is finally ready to be merged.

**Comment by florianpircher** [comment]
Sorry, I’ve been sick the last few days and didn’t see your progress. I will test again tomorrow or Thursday and merge.

**Comment by florianpircher** [comment]
Merci !

**Pull request merged**
