### PR TITLE
add new plugin : Change Sentence To Mieum

### PR DESCRIPTION
**Pull request by sindpfla98**
add new plugin = Change Sentence To Mieum

### CODE REVIEW

**Comment by florianpircher** [comment]
Hi, thank you for adding the plugin!

In the description, you write that for Intel, instructions are on the GitHub page, but I cannot find them. What needs to be done to install the plugin on Intel Macs?

**Comment by sindpfla98** [comment]
https://github.com/sindpfla98/ChangeSentenceToMieum?tab=readme-ov-file#for-intel-installation

I have written the file and how to install it here.

**Comment by florianpircher** [comment]
In that case, you could also add two entries to the package index; one with an `archs` list of just `arm` and one with `archs` of just `intel`. M1/M2/M3/… users will just be shown the ARM entry, and Intel users will only see the Intel entry.

For this, you would need to add the Intel version of your plugin to the repository.

## Option 1

Name the Intel version ChangeSentenceToMieum-Intel.glyphsPlugin (or similar). In the package index, add a duplicate entry, changing the `path` to match the Intel version and `archs` to `( intel )`.

## Option 2

Create a second branch in your ChangeSentenceToMieum repository and place the intel version there. In the package index, add a duplicate entry, adding `branch = intel;` and changing `archs` to `( intel )`.

***

I think I prefer option 2, but option 1 works well, too. I can change the package index for you, if you would like, but since I have no access to your ChangeSentenceToMieum repository, you would need to do the first step of option 1 or 2.

Or, if you don’t want to maintain both the ARM and Intel versions in the repository, that is fine too, and I will merge this pull request immediately.

**Comment by sindpfla98** [comment]
Thank you for telling me the new way. I'll try with the option 2 you recommended.

**Comment by florianpircher** [comment]
Thank you very much!

**Comment by schriftgestalt** [comment]
it should be possible to build a universal version of the plugin. I found this that explains the process and some trouble shooting: https://github.com/dashingsoft/pyarmor/discussions/1408

**Comment by sindpfla98** [comment]
Thank you, the way you told me seems to work very well, I'll update this again soon.

**Pull request merged**
