### PR TITLE
Fixes typo in "Fill Background Path" plugin description and adds note about using plutil to test first

### PR DESCRIPTION
**Pull request by composerjk**

### CODE REVIEW

**Comment by schriftgestalt** [comment]
Do you know if it is possible to run something like plutil as automatic test in GitHub?

**Comment by composerjk** [comment]
The simplest would be to add a pre-commit hook to run plutil before each commit, though that happens in one's local copy. Since that's stored outside the repository, it would have to be manually installed. The simplest script would be stored in `.git/hooks/pre-commit` (with file mode set to exectuable: `chmod a+x .git/hooks/pre-commit`):

```
#!/bin/sh

exec plutil -lint packages.plist
```

Technically, the `-lint` argument is the default if no other option is specified, but I like to be specific. Since this repository is small, I figured hard-coding the filename was fine.

We could add a sample `pre-commit` script to the repository with instructions for copying it to the proper location and making it executable for those that might be adding multiple plugins over time. When installed, if `plutil` fails, then the `git commit` will not do the commit, locally.

Without setting up a Continuous Integration server or a server that handles the Status API, I don't think there's a simple way in GitHub to have that run, though it's possible there's something I haven't run across.

**Comment by schriftgestalt** [comment]
The glyphsLib repo has continuous integration. I tried that but couldn’t find a none Mac tool that could be used. But maybe we can use the parser from glyphLib?

**Comment by composerjk** [comment]
Using glyphsLib could be possible. I'd have to glance at the code base. When I wrote code to parse the `.glyphs` file, I cheated and used NSPropertyListSerialization since I knew I'd only be running on macOS and to get something available quickly.

It doesn't look like the libplist library has added support for the NeXTStep property list format, yet:
https://github.com/libimobiledevice/libplist

Though I haven't looked through the code, there's this pbPlist Python module that does support the old NeXTStep property list format that you use:
https://github.com/samdmarshall/pbPlist

With the pbPlist module, something like this might work. The line number reported for parsing issues might be slightly off. It reported the line number for the beginning of the block when the description attribute was missing the escaped quote, though that might be fine.
```
#!/usr/bin/env python3
#

import sys
from pbPlist import pbPlist

try:
	# purposely throwing away the return of PBPlist since we're just checking that it parses
	z = pbPlist.PBPlist("packages.plist")
except Exception as e:
	print(e)
	sys.exit(1)
```

**Comment by schriftgestalt** [comment]
I think I figured it out. Now we need a broken pul request to see if it works.

**Pull request merged**
