### PR TITLE
add SmartSelectTool

### PR DESCRIPTION
**Pull request by ButTaiwan**

### CODE REVIEW

**Comment by schriftgestalt** [comment]
Please always put the new entries at the end of the list. And try to not change stuff in entries that don’t belong to you. Thanks

**Comment by ButTaiwan** [comment]
Yes, I noticed that you adjust the order last time, so I tried to append new entry below my last stuff yesterday.

However, I don't know why GitHub keep my original order when I merged my fork from upstream.
I have no idea how to fix the problem. Finally, I copied all text from Chrome to my file to keep the order as latest one.
I am sorry for it looks like an empty character (?) was modified when copying the whole data.

**Comment by schriftgestalt** [comment]
If the repo is confused like this, it is sometimes better to start over. Ether reset it to the origin, or even delete your fork and make a new one.

And only edit the packages file in a text editor, not in Xcode. 

And when you do the commit, check if there are only intended changes and remove the wrong ones. That is very easy in the GitHub app or Transmit (or any other git app).

**Comment by ButTaiwan** [comment]
Thanks for your suggestion.

I merged the latest upstream again, and it looks working well this time.

**Pull request merged**
