### PR TITLE
add Context Manager Plugin

### PR DESCRIPTION
**Pull request by HugoJourdan**
> **Note**: Please add new plugins and scripts at the end of the `plugins = ( ... )` or `scripts = ( ... )` lists.

### CODE REVIEW

**Comment by HugoJourdan** [comment]
Fix small problem

**Comment by florianpircher** [comment]
Please add new entries at the end of the plugins list, otherwise looks good.

**Comment by florianpircher** [comment]
The plugin crashes on first run because some file is missing. Can you look into this:

Bildschirmfoto 2022-10-27 um 13 27 24

**Comment by HugoJourdan** [comment]
It was fixed but I forget to commit change.
Now it should work !

**Comment by florianpircher** [comment]
It does not work if the user default value is not set. Register default values when the plugin is loaded like so:

```python
Glyphs.registerDefault("some-key", 5) # default value is 5
```

Bildschirmfoto 2022-10-27 um 13 32 54

**Comment by HugoJourdan** [comment]
Fixed.

**Pull request merged**
